### PR TITLE
Integrating Ledger wallet into index coop natively - part 1

### PR DESCRIPTION
**Pull request by FlattestWhite**
# **Pull Request Template**

###### *Select a category that relates to the content of your pull request (choose all that apply).*

- [ ] Bug Fix
- [ ] Content
- [x] New Feature
- [ ] Documentation
- [ ] Code Refactoring

&nbsp;

###### *Provide a brief summary of the changes you made and their purpose as they relate to Index UI. <br/>If applicable, please link the corresponding issue number.*

Related to this ticket:
https://www.notion.so/Implement-Ledger-Support-for-Index-UI-24ce82134b854edf921dc4e9dbbf1269

Decided to go with WebUSB because WebHID is still not available in Chrome generally. Most users use Chrome as their primary browser, hence implementing WebUSB is currently more effective.

Summary of changes so far:
1. Added a card in the WalletProvider so that it shows up as a wallet option
2. Added an image for ledger wallet
3. Added a LedgerConnector implementation of an AbstractConnector
4. Added a LedgerSubprovider leveraging 0x's BaseWalletSubprovider as the base
5. Leverages ledgerjs WebUSB library and their eth library

Still to be done:
1. Implement signTransactionAsync in LedgerSubprovider
2. Implement signPersonalMessageAsync in LedgerSubprovider
3. Implement signTypedDataAsync in LedgerSubprovider

Open questions:
1. The user needs to be signed into their ledger wallet and have the ethereum app open. Ideally, we show them an error message and guide them to do so if they haven't opened. However, I can't seem to find where error handling happens.
2. Are there currently feature flag capabilities so that new features can be rolled out behind a flag?

&nbsp;

### **Fixes: Issue #**

&nbsp;

###### *Include proof that your changes function properly and resolve the linked issue.*

Added a video showing how it connected to the device.

&nbsp;

###### *By submitting this pull request, you are confirming the following to be true:*

- I have reviewed the [Contribution Guidelines](https://github.com/SetProtocol/index-ui/blob/master/CONTRIBUTING.md).
- I have performed a self-review of my own code.
- I have updated my repository to match the master at `SetProtocol/index-ui`.
- I have included test data or screenshots that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by FlattestWhite** [comment]
https://user-images.githubusercontent.com/33583612/134758288-9699224c-ad16-43af-b09d-c8008cd538a8.mp4

**Comment by FlattestWhite** [comment]
@0xModene ready for initial review

**Comment by 0xModene** [comment]
This looks great! Ledger support will be huge. 

So far I've got 2 points of feedback, one of which you may be aware of: 

1) I can't see my wallet balances when connecting via the Ledger. You may know this already and plan to address it in a future push
Screen Shot 2021-09-27 at 10 16 38 AM



2) Since this is a 'Part 1' I went ahead and created a [ledger-integration](https://github.com/SetProtocol/index-ui/tree/ledger-integration) branch. Can you change this PR to point to that branch instead of master? We'll put everything in there until it's completed and test that way before merging into master.

**Review by 0xModene — CHANGES_REQUESTED** [review]
see other comment for requested changes

**Review by 0xModene — APPROVED** [review]

**Pull request merged**
