### PR TITLE
Fix width of Integrations cards

### PR DESCRIPTION
**Pull request by ncitron**
## Changes
- Fixed width of integrations cards which were misaligned with the cards further up the page.
- Fixed typo

### CODE REVIEW

**Comment by controtie** [comment]
Do you have a screen shot of the alignment issues this PR addresses?

Also this PR changes the alignment of these bottom cards. Ideally we want 3 card per row
image

**Comment by ncitron** [comment]
If you look closely, notice how the right edges of the rightmost cards are misaligned with the horizontal rule.

Screen Shot 2020-11-26 at 12 23 51 PM

I can fix the problem with the four cards in the last row. Would you prefer it look like this:

Screen Shot 2020-11-26 at 12 28 59 PM

Or this:

Screen Shot 2020-11-26 at 12 27 07 PM

**Comment by controtie** [comment]
The first one looks good. Want to keep all the cards the same length. (imagine if there were two cards in the last row, might look weird if it was filled)

**Comment by ncitron** [comment]
It should be good to go now.

**Review by controtie — APPROVED** [review]
LGTM

**Pull request merged**
