### PR TITLE
Add link to institutional page

### PR DESCRIPTION
**Pull request by pouta**
# **Pull Request Template**

## **Type of Change**

*Select a category that relates to the content of your pull request (choose one).*

- [ ] Bug fix
- [x] New feature
- [ ] Documentation
- [ ] Code Refactoring
- [ ] Update of code styling

&nbsp;

## **Does this request include a breaking change?**

*Is there any potential for this change to crash Index UI or make it unusable?*

- [ ] Yes
- [x] No

&nbsp;

## **Description**

Adds link to institutional webpage on nav bar

&nbsp;

## **Checklist**

*Please review and confirm each of the following before creating your pull request.*

- [x] I have reviewed the [Contribution Guidelines](https://github.com/SetProtocol/index-ui/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have checked my code and corrected any errors.
- [x] I have commented my code or used an effective naming scheme.
- [x] I have updated my repository to match the master at `SetProtocol/index-ui`.
- [ ] I have included test data or screenshots that prove my fix is effective or that my feature works.

&nbsp;

*If all of the above are **true**, then you may mark your pull request as **ready for review**.*

### CODE REVIEW

**Review by 0xModene — APPROVED** [review]
lgtm

**Comment by 0xModene** [comment]
@controtie ready to merge when you are

**Comment by controtie** [comment]
Yup, this will go in once institutions page has been set up on cloudflare & s3

**Comment by 0xModene** [comment]
I'm closing this as it was merged in alongside #281

**Pull request closed without merging**
